//
// File generated by /Users/adam/softwareDev/root/v5.26.00b/bin/rootcint at Fri Aug 27 16:24:26 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "kpsa_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void KPsaProcessor_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void KPsaProcessor_Dictionary();

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::KPsaProcessor*)
   {
      ::KPsaProcessor *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::KPsaProcessor),0);
      static ::ROOT::TGenericClassInfo 
         instance("KPsaProcessor", "kpsa/KPsaProcessor.h", 19,
                  typeid(::KPsaProcessor), DefineBehavior(ptr, ptr),
                  0, &KPsaProcessor_Dictionary, isa_proxy, 0,
                  sizeof(::KPsaProcessor) );
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::KPsaProcessor*)
   {
      return GenerateInitInstanceLocal((::KPsaProcessor*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::KPsaProcessor*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void KPsaProcessor_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::KPsaProcessor*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void KBaselineRemoval_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void KBaselineRemoval_Dictionary();
   static void *new_KBaselineRemoval(void *p = 0);
   static void *newArray_KBaselineRemoval(Long_t size, void *p);
   static void delete_KBaselineRemoval(void *p);
   static void deleteArray_KBaselineRemoval(void *p);
   static void destruct_KBaselineRemoval(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::KBaselineRemoval*)
   {
      ::KBaselineRemoval *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::KBaselineRemoval),0);
      static ::ROOT::TGenericClassInfo 
         instance("KBaselineRemoval", "kpsa/KBaselineRemoval.h", 16,
                  typeid(::KBaselineRemoval), DefineBehavior(ptr, ptr),
                  0, &KBaselineRemoval_Dictionary, isa_proxy, 0,
                  sizeof(::KBaselineRemoval) );
      instance.SetNew(&new_KBaselineRemoval);
      instance.SetNewArray(&newArray_KBaselineRemoval);
      instance.SetDelete(&delete_KBaselineRemoval);
      instance.SetDeleteArray(&deleteArray_KBaselineRemoval);
      instance.SetDestructor(&destruct_KBaselineRemoval);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::KBaselineRemoval*)
   {
      return GenerateInitInstanceLocal((::KBaselineRemoval*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::KBaselineRemoval*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void KBaselineRemoval_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::KBaselineRemoval*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void KPatternRemoval_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void KPatternRemoval_Dictionary();
   static void *new_KPatternRemoval(void *p = 0);
   static void *newArray_KPatternRemoval(Long_t size, void *p);
   static void delete_KPatternRemoval(void *p);
   static void deleteArray_KPatternRemoval(void *p);
   static void destruct_KPatternRemoval(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::KPatternRemoval*)
   {
      ::KPatternRemoval *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::KPatternRemoval),0);
      static ::ROOT::TGenericClassInfo 
         instance("KPatternRemoval", "kpsa/KPatternRemoval.h", 16,
                  typeid(::KPatternRemoval), DefineBehavior(ptr, ptr),
                  0, &KPatternRemoval_Dictionary, isa_proxy, 0,
                  sizeof(::KPatternRemoval) );
      instance.SetNew(&new_KPatternRemoval);
      instance.SetNewArray(&newArray_KPatternRemoval);
      instance.SetDelete(&delete_KPatternRemoval);
      instance.SetDeleteArray(&deleteArray_KPatternRemoval);
      instance.SetDestructor(&destruct_KPatternRemoval);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::KPatternRemoval*)
   {
      return GenerateInitInstanceLocal((::KPatternRemoval*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::KPatternRemoval*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void KPatternRemoval_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::KPatternRemoval*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void KPulseAnalysisChain_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void KPulseAnalysisChain_Dictionary();
   static void *new_KPulseAnalysisChain(void *p = 0);
   static void *newArray_KPulseAnalysisChain(Long_t size, void *p);
   static void delete_KPulseAnalysisChain(void *p);
   static void deleteArray_KPulseAnalysisChain(void *p);
   static void destruct_KPulseAnalysisChain(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::KPulseAnalysisChain*)
   {
      ::KPulseAnalysisChain *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::KPulseAnalysisChain),0);
      static ::ROOT::TGenericClassInfo 
         instance("KPulseAnalysisChain", "kpsa/KPulseAnalysisChain.h", 19,
                  typeid(::KPulseAnalysisChain), DefineBehavior(ptr, ptr),
                  0, &KPulseAnalysisChain_Dictionary, isa_proxy, 0,
                  sizeof(::KPulseAnalysisChain) );
      instance.SetNew(&new_KPulseAnalysisChain);
      instance.SetNewArray(&newArray_KPulseAnalysisChain);
      instance.SetDelete(&delete_KPulseAnalysisChain);
      instance.SetDeleteArray(&deleteArray_KPulseAnalysisChain);
      instance.SetDestructor(&destruct_KPulseAnalysisChain);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::KPulseAnalysisChain*)
   {
      return GenerateInitInstanceLocal((::KPulseAnalysisChain*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::KPulseAnalysisChain*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void KPulseAnalysisChain_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::KPulseAnalysisChain*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void KRealToHalfComplexDFT_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void KRealToHalfComplexDFT_Dictionary();
   static void *new_KRealToHalfComplexDFT(void *p = 0);
   static void *newArray_KRealToHalfComplexDFT(Long_t size, void *p);
   static void delete_KRealToHalfComplexDFT(void *p);
   static void deleteArray_KRealToHalfComplexDFT(void *p);
   static void destruct_KRealToHalfComplexDFT(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::KRealToHalfComplexDFT*)
   {
      ::KRealToHalfComplexDFT *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::KRealToHalfComplexDFT),0);
      static ::ROOT::TGenericClassInfo 
         instance("KRealToHalfComplexDFT", "kpsa/KRealToHalfComplexDFT.h", 16,
                  typeid(::KRealToHalfComplexDFT), DefineBehavior(ptr, ptr),
                  0, &KRealToHalfComplexDFT_Dictionary, isa_proxy, 0,
                  sizeof(::KRealToHalfComplexDFT) );
      instance.SetNew(&new_KRealToHalfComplexDFT);
      instance.SetNewArray(&newArray_KRealToHalfComplexDFT);
      instance.SetDelete(&delete_KRealToHalfComplexDFT);
      instance.SetDeleteArray(&deleteArray_KRealToHalfComplexDFT);
      instance.SetDestructor(&destruct_KRealToHalfComplexDFT);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::KRealToHalfComplexDFT*)
   {
      return GenerateInitInstanceLocal((::KRealToHalfComplexDFT*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::KRealToHalfComplexDFT*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void KRealToHalfComplexDFT_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::KRealToHalfComplexDFT*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_KBaselineRemoval(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KBaselineRemoval : new ::KBaselineRemoval;
   }
   static void *newArray_KBaselineRemoval(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KBaselineRemoval[nElements] : new ::KBaselineRemoval[nElements];
   }
   // Wrapper around operator delete
   static void delete_KBaselineRemoval(void *p) {
      delete ((::KBaselineRemoval*)p);
   }
   static void deleteArray_KBaselineRemoval(void *p) {
      delete [] ((::KBaselineRemoval*)p);
   }
   static void destruct_KBaselineRemoval(void *p) {
      typedef ::KBaselineRemoval current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::KBaselineRemoval

namespace ROOT {
   // Wrappers around operator new
   static void *new_KPatternRemoval(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KPatternRemoval : new ::KPatternRemoval;
   }
   static void *newArray_KPatternRemoval(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KPatternRemoval[nElements] : new ::KPatternRemoval[nElements];
   }
   // Wrapper around operator delete
   static void delete_KPatternRemoval(void *p) {
      delete ((::KPatternRemoval*)p);
   }
   static void deleteArray_KPatternRemoval(void *p) {
      delete [] ((::KPatternRemoval*)p);
   }
   static void destruct_KPatternRemoval(void *p) {
      typedef ::KPatternRemoval current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::KPatternRemoval

namespace ROOT {
} // end of namespace ROOT for class ::KPsaProcessor

namespace ROOT {
   // Wrappers around operator new
   static void *new_KPulseAnalysisChain(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KPulseAnalysisChain : new ::KPulseAnalysisChain;
   }
   static void *newArray_KPulseAnalysisChain(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KPulseAnalysisChain[nElements] : new ::KPulseAnalysisChain[nElements];
   }
   // Wrapper around operator delete
   static void delete_KPulseAnalysisChain(void *p) {
      delete ((::KPulseAnalysisChain*)p);
   }
   static void deleteArray_KPulseAnalysisChain(void *p) {
      delete [] ((::KPulseAnalysisChain*)p);
   }
   static void destruct_KPulseAnalysisChain(void *p) {
      typedef ::KPulseAnalysisChain current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::KPulseAnalysisChain

namespace ROOT {
   // Wrappers around operator new
   static void *new_KRealToHalfComplexDFT(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KRealToHalfComplexDFT : new ::KRealToHalfComplexDFT;
   }
   static void *newArray_KRealToHalfComplexDFT(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KRealToHalfComplexDFT[nElements] : new ::KRealToHalfComplexDFT[nElements];
   }
   // Wrapper around operator delete
   static void delete_KRealToHalfComplexDFT(void *p) {
      delete ((::KRealToHalfComplexDFT*)p);
   }
   static void deleteArray_KRealToHalfComplexDFT(void *p) {
      delete [] ((::KRealToHalfComplexDFT*)p);
   }
   static void destruct_KRealToHalfComplexDFT(void *p) {
      typedef ::KRealToHalfComplexDFT current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::KRealToHalfComplexDFT

/********************************************************
* kpsa/kpsa_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablekpsa_Dict();

extern "C" void G__set_cpp_environmentkpsa_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("kpsa/KBaselineRemoval.h");
  G__add_compiledheader("kpsa/KPatternRemoval.h");
  G__add_compiledheader("kpsa/KPsaProcessor.h");
  G__add_compiledheader("kpsa/KPulseAnalysisChain.h");
  G__add_compiledheader("kpsa/KRealToHalfComplexDFT.h");
  G__cpp_reset_tagtablekpsa_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevkpsa_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* KPsaProcessor */
static int G__kpsa_Dict_159_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPsaProcessor*) G__getstructoffset())->SetInputPulse(*(vector<double>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPsaProcessor*) G__getstructoffset())->SetInputPulse(*(vector<short>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPsaProcessor*) G__getstructoffset())->SetInputPulse(*(vector<float>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPsaProcessor*) G__getstructoffset())->SetInputPulse(*(vector<int>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPsaProcessor*) G__getstructoffset())->SetInputPulse((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<double>* pobj;
         const vector<double> xobj = ((const KPsaProcessor*) G__getstructoffset())->GetOutputPulse();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const KPsaProcessor*) G__getstructoffset())->GetOutputPulse(*(vector<float>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<double>* pobj;
         const vector<double> xobj = ((const KPsaProcessor*) G__getstructoffset())->GetInputPulse();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const KPsaProcessor*) G__getstructoffset())->GetInputPulse(*(vector<float>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KPsaProcessor*) G__getstructoffset())->RunProcess());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((const KPsaProcessor*) G__getstructoffset())->GetName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_159_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPsaProcessor*) G__getstructoffset())->SetName((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__kpsa_Dict_159_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KPsaProcessor* dest = (KPsaProcessor*) G__getstructoffset();
   *dest = *(KPsaProcessor*) libp->para[0].ref;
   const KPsaProcessor& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* KBaselineRemoval */
static int G__kpsa_Dict_164_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KBaselineRemoval* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KBaselineRemoval[n];
     } else {
       p = new((void*) gvp) KBaselineRemoval[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KBaselineRemoval;
     } else {
       p = new((void*) gvp) KBaselineRemoval;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__kpsa_DictLN_KBaselineRemoval));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_164_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const KBaselineRemoval*) G__getstructoffset())->CalculateAverage());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_164_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KBaselineRemoval*) G__getstructoffset())->Subtract((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_164_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const KBaselineRemoval*) G__getstructoffset())->GetBaselineStart());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_164_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const KBaselineRemoval*) G__getstructoffset())->GetBaselineStop());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_164_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KBaselineRemoval*) G__getstructoffset())->GetBaselineStart((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_164_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KBaselineRemoval*) G__getstructoffset())->GetBaselineStop((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__kpsa_Dict_164_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   KBaselineRemoval* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new KBaselineRemoval(*(KBaselineRemoval*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__kpsa_DictLN_KBaselineRemoval));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef KBaselineRemoval G__TKBaselineRemoval;
static int G__kpsa_Dict_164_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (KBaselineRemoval*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((KBaselineRemoval*) (soff+(sizeof(KBaselineRemoval)*i)))->~G__TKBaselineRemoval();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (KBaselineRemoval*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((KBaselineRemoval*) (soff))->~G__TKBaselineRemoval();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__kpsa_Dict_164_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KBaselineRemoval* dest = (KBaselineRemoval*) G__getstructoffset();
   *dest = *(KBaselineRemoval*) libp->para[0].ref;
   const KBaselineRemoval& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* KPatternRemoval */
static int G__kpsa_Dict_165_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KPatternRemoval* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KPatternRemoval[n];
     } else {
       p = new((void*) gvp) KPatternRemoval[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KPatternRemoval;
     } else {
       p = new((void*) gvp) KPatternRemoval;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__kpsa_DictLN_KPatternRemoval));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KPatternRemoval*) G__getstructoffset())->CalculatePattern());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KPatternRemoval*) G__getstructoffset())->SubtractPattern());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KPatternRemoval*) G__getstructoffset())->SubtractPattern(*(vector<double>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const KPatternRemoval*) G__getstructoffset())->GetPatternLength());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const KPatternRemoval*) G__getstructoffset())->GetBaselineStart());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const KPatternRemoval*) G__getstructoffset())->GetBaselineStop());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<double>* pobj;
         const vector<double> xobj = ((const KPatternRemoval*) G__getstructoffset())->GetPattern();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPatternRemoval*) G__getstructoffset())->SetPatternLength((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPatternRemoval*) G__getstructoffset())->SetBaselineStart((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPatternRemoval*) G__getstructoffset())->SetBaselineStop((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KPatternRemoval*) G__getstructoffset())->SetPattern(*(vector<double>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KPatternRemoval*) G__getstructoffset())->SetPattern(*(vector<short>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KPatternRemoval*) G__getstructoffset())->SetPattern(*(vector<float>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_165_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((KPatternRemoval*) G__getstructoffset())->SetPattern(*(vector<int>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__kpsa_Dict_165_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   KPatternRemoval* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new KPatternRemoval(*(KPatternRemoval*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__kpsa_DictLN_KPatternRemoval));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef KPatternRemoval G__TKPatternRemoval;
static int G__kpsa_Dict_165_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (KPatternRemoval*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((KPatternRemoval*) (soff+(sizeof(KPatternRemoval)*i)))->~G__TKPatternRemoval();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (KPatternRemoval*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((KPatternRemoval*) (soff))->~G__TKPatternRemoval();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__kpsa_Dict_165_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KPatternRemoval* dest = (KPatternRemoval*) G__getstructoffset();
   *dest = *(KPatternRemoval*) libp->para[0].ref;
   const KPatternRemoval& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* KPulseAnalysisChain */
static int G__kpsa_Dict_166_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KPulseAnalysisChain* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KPulseAnalysisChain[n];
     } else {
       p = new((void*) gvp) KPulseAnalysisChain[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KPulseAnalysisChain;
     } else {
       p = new((void*) gvp) KPulseAnalysisChain;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__kpsa_DictLN_KPulseAnalysisChain));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_166_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((KPulseAnalysisChain*) G__getstructoffset())->RunAll());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_166_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPulseAnalysisChain*) G__getstructoffset())->AddProcessor((KPsaProcessor*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_166_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KPulseAnalysisChain*) G__getstructoffset())->AddProcessorAt((KPsaProcessor*) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__kpsa_Dict_166_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   KPulseAnalysisChain* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new KPulseAnalysisChain(*(KPulseAnalysisChain*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__kpsa_DictLN_KPulseAnalysisChain));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef KPulseAnalysisChain G__TKPulseAnalysisChain;
static int G__kpsa_Dict_166_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (KPulseAnalysisChain*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((KPulseAnalysisChain*) (soff+(sizeof(KPulseAnalysisChain)*i)))->~G__TKPulseAnalysisChain();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (KPulseAnalysisChain*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((KPulseAnalysisChain*) (soff))->~G__TKPulseAnalysisChain();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__kpsa_Dict_166_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KPulseAnalysisChain* dest = (KPulseAnalysisChain*) G__getstructoffset();
   *dest = *(KPulseAnalysisChain*) libp->para[0].ref;
   const KPulseAnalysisChain& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* KRealToHalfComplexDFT */
static int G__kpsa_Dict_171_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KRealToHalfComplexDFT* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KRealToHalfComplexDFT[n];
     } else {
       p = new((void*) gvp) KRealToHalfComplexDFT[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KRealToHalfComplexDFT;
     } else {
       p = new((void*) gvp) KRealToHalfComplexDFT;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__kpsa_DictLN_KRealToHalfComplexDFT));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_171_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((KRealToHalfComplexDFT*) G__getstructoffset())->SetFFTWFlag((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((KRealToHalfComplexDFT*) G__getstructoffset())->SetFFTWFlag();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_171_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const KRealToHalfComplexDFT*) G__getstructoffset())->GetIn_fft());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_171_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 68, (long) ((const KRealToHalfComplexDFT*) G__getstructoffset())->GetOut_fft());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kpsa_Dict_171_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((KRealToHalfComplexDFT*) G__getstructoffset())->GetFFTWFlag());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__kpsa_Dict_171_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   KRealToHalfComplexDFT* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new KRealToHalfComplexDFT(*(KRealToHalfComplexDFT*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__kpsa_DictLN_KRealToHalfComplexDFT));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef KRealToHalfComplexDFT G__TKRealToHalfComplexDFT;
static int G__kpsa_Dict_171_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (KRealToHalfComplexDFT*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((KRealToHalfComplexDFT*) (soff+(sizeof(KRealToHalfComplexDFT)*i)))->~G__TKRealToHalfComplexDFT();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (KRealToHalfComplexDFT*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((KRealToHalfComplexDFT*) (soff))->~G__TKRealToHalfComplexDFT();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__kpsa_Dict_171_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KRealToHalfComplexDFT* dest = (KRealToHalfComplexDFT*) G__getstructoffset();
   *dest = *(KRealToHalfComplexDFT*) libp->para[0].ref;
   const KRealToHalfComplexDFT& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* KPsaProcessor */

/* KBaselineRemoval */

/* KPatternRemoval */

/* KPulseAnalysisChain */

/* KRealToHalfComplexDFT */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunckpsa_Dict {
 public:
  G__Sizep2memfunckpsa_Dict(): p(&G__Sizep2memfunckpsa_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunckpsa_Dict::*p)();
};

size_t G__get_sizep2memfunckpsa_Dict()
{
  G__Sizep2memfunckpsa_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancekpsa_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__kpsa_DictLN_KBaselineRemoval))) {
     KBaselineRemoval *G__Lderived;
     G__Lderived=(KBaselineRemoval*)0x1000;
     {
       KPsaProcessor *G__Lpbase=(KPsaProcessor*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KBaselineRemoval),G__get_linked_tagnum(&G__kpsa_DictLN_KPsaProcessor),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__kpsa_DictLN_KPatternRemoval))) {
     KPatternRemoval *G__Lderived;
     G__Lderived=(KPatternRemoval*)0x1000;
     {
       KPsaProcessor *G__Lpbase=(KPsaProcessor*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KPatternRemoval),G__get_linked_tagnum(&G__kpsa_DictLN_KPsaProcessor),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__kpsa_DictLN_KRealToHalfComplexDFT))) {
     KRealToHalfComplexDFT *G__Lderived;
     G__Lderived=(KRealToHalfComplexDFT*)0x1000;
     {
       KPsaProcessor *G__Lpbase=(KPsaProcessor*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KRealToHalfComplexDFT),G__get_linked_tagnum(&G__kpsa_DictLN_KPsaProcessor),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablekpsa_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__kpsa_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__kpsa_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__kpsa_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__kpsa_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<KPsaProcessor*>",117,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__kpsa_DictLN_reverse_iteratorlEvectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__kpsa_DictLN_reverse_iteratorlEvectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* KPsaProcessor */
static void G__setup_memvarKPsaProcessor(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KPsaProcessor));
   { KPsaProcessor *p; p=(KPsaProcessor*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__kpsa_DictLN_string),-1,-1,2,"fProcessorName=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fInputPulse=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fOutputPulse=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* KBaselineRemoval */
static void G__setup_memvarKBaselineRemoval(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KBaselineRemoval));
   { KBaselineRemoval *p; p=(KBaselineRemoval*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fBaselineStart=",0,"starting position of region to be averaged for baseline subtraction, in percent of the total pulse length");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fBaselineStop=",0,"stoping position of region to be averaged for baseline subtraction, in percent of the total pulse length");
   }
   G__tag_memvar_reset();
}


   /* KPatternRemoval */
static void G__setup_memvarKPatternRemoval(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KPatternRemoval));
   { KPatternRemoval *p; p=(KPatternRemoval*)0x1000; if (p) { }
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"fPatternLength=",0,"used primarily for the CalculatePattern routine. Whenever you call SetPattern, this value is changed to match the length of the pattern you passed in.");
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"fBaselineStart=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"fBaselineStop=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fPattern=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* KPulseAnalysisChain */
static void G__setup_memvarKPulseAnalysisChain(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KPulseAnalysisChain));
   { KPulseAnalysisChain *p; p=(KPulseAnalysisChain*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgR),G__defined_typename("vector<KPsaProcessor*>"),-1,4,"fProcessorList=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* KRealToHalfComplexDFT */
static void G__setup_memvarKRealToHalfComplexDFT(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KRealToHalfComplexDFT));
   { KRealToHalfComplexDFT *p; p=(KRealToHalfComplexDFT*)0x1000; if (p) { }
   G__memvar_setup((void*)0,89,0,0,-1,-1,-1,4,"fPlan=",0,"points to the fftw_plan ");
   G__memvar_setup((void*)0,68,0,0,-1,-1,-1,4,"fIn_fft=",0,"all real input");
   G__memvar_setup((void*)0,68,0,0,-1,-1,-1,4,"fOut_fft=",0,"in half-complex format");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__kpsa_DictLN_string),-1,-1,4,"fFFTWFlag=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarkpsa_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncKPsaProcessor(void) {
   /* KPsaProcessor */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KPsaProcessor));
   G__memfunc_setup("SetInputPulse",1349,G__kpsa_Dict_159_0_1, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - aPulse", "Set the input pulse", (void*) NULL, 1);
   G__memfunc_setup("SetInputPulse",1349,G__kpsa_Dict_159_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<short,allocator<short> >' 'vector<short>' 11 - aPulse", "Set the input pulse ", (void*) NULL, 1);
   G__memfunc_setup("SetInputPulse",1349,G__kpsa_Dict_159_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<float,allocator<float> >' 'vector<float>' 11 - aPulse", "Set the input pulse", (void*) NULL, 1);
   G__memfunc_setup("SetInputPulse",1349,G__kpsa_Dict_159_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<int,allocator<int> >' 'vector<int>' 11 - aPulse", "Set the input pulse", (void*) NULL, 1);
   G__memfunc_setup("SetInputPulse",1349,G__kpsa_Dict_159_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - aFile", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputPulse",1466,G__kpsa_Dict_159_0_6, 117, G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 8, "", "obtain a copy of the output pulse with double precision", (void*) NULL, 1);
   G__memfunc_setup("GetOutputPulse",1466,G__kpsa_Dict_159_0_7, 121, -1, -1, 0, 1, 1, 1, 8, "u 'vector<float,allocator<float> >' 'vector<float>' 1 - myPulse", "demote the precision and obtian a copy of the output pulse in single precision", (void*) NULL, 1);
   G__memfunc_setup("GetInputPulse",1337,G__kpsa_Dict_159_0_8, 117, G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 8, "", "obtain a copy of the input pulse", (void*) NULL, 1);
   G__memfunc_setup("GetInputPulse",1337,G__kpsa_Dict_159_0_9, 121, -1, -1, 0, 1, 1, 1, 8, "u 'vector<float,allocator<float> >' 'vector<float>' 1 - myPulse", "demote the precision and obtian a copy of the output pulse in single precision", (void*) NULL, 1);
   G__memfunc_setup("RunProcess",1044,G__kpsa_Dict_159_0_10, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 3);
   G__memfunc_setup("GetName",673,G__kpsa_Dict_159_0_11, 67, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetName",685,G__kpsa_Dict_159_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - aName", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitializeMembers",1757,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__kpsa_Dict_159_0_15, (int) ('u'), G__get_linked_tagnum(&G__kpsa_DictLN_KPsaProcessor), -1, 1, 1, 1, 1, 0, "u 'KPsaProcessor' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncKBaselineRemoval(void) {
   /* KBaselineRemoval */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KBaselineRemoval));
   G__memfunc_setup("KBaselineRemoval",1604,G__kpsa_Dict_164_0_1, 105, G__get_linked_tagnum(&G__kpsa_DictLN_KBaselineRemoval), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunProcess",1044,(G__InterfaceMethod) NULL,103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CalculateAverage",1609,G__kpsa_Dict_164_0_3, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Subtract",840,G__kpsa_Dict_164_0_4, 103, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - aVal", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetBaselineStart",1617,G__kpsa_Dict_164_0_5, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBaselineStop",1513,G__kpsa_Dict_164_0_6, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBaselineStart",1617,G__kpsa_Dict_164_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - aVal", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetBaselineStop",1513,G__kpsa_Dict_164_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - aVal", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitializeMembers",1757,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("KBaselineRemoval", 1604, G__kpsa_Dict_164_0_10, (int) ('i'), G__get_linked_tagnum(&G__kpsa_DictLN_KBaselineRemoval), -1, 0, 1, 1, 1, 0, "u 'KBaselineRemoval' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~KBaselineRemoval", 1730, G__kpsa_Dict_164_0_11, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__kpsa_Dict_164_0_12, (int) ('u'), G__get_linked_tagnum(&G__kpsa_DictLN_KBaselineRemoval), -1, 1, 1, 1, 1, 0, "u 'KBaselineRemoval' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncKPatternRemoval(void) {
   /* KPatternRemoval */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KPatternRemoval));
   G__memfunc_setup("KPatternRemoval",1535,G__kpsa_Dict_165_0_1, 105, G__get_linked_tagnum(&G__kpsa_DictLN_KPatternRemoval), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunProcess",1044,(G__InterfaceMethod) NULL,103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CalculatePattern",1644,G__kpsa_Dict_165_0_3, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SubtractPattern",1574,G__kpsa_Dict_165_0_4, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SubtractPattern",1574,G__kpsa_Dict_165_0_5, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 1 - aPattern", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetPatternLength",1632,G__kpsa_Dict_165_0_6, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetBaselineStart",1617,G__kpsa_Dict_165_0_7, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetBaselineStop",1513,G__kpsa_Dict_165_0_8, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetPattern",1022,G__kpsa_Dict_165_0_9, 117, G__get_linked_tagnum(&G__kpsa_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetPatternLength",1644,G__kpsa_Dict_165_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - aLength", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetBaselineStart",1629,G__kpsa_Dict_165_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - aVal", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetBaselineStop",1525,G__kpsa_Dict_165_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - aVal", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetPattern",1034,G__kpsa_Dict_165_0_13, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 1 - aPattern", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetPattern",1034,G__kpsa_Dict_165_0_14, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<short,allocator<short> >' 'vector<short>' 1 - aPulse", "Set the pattern ", (void*) NULL, 1);
   G__memfunc_setup("SetPattern",1034,G__kpsa_Dict_165_0_15, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<float,allocator<float> >' 'vector<float>' 1 - aPulse", "Set the pattern", (void*) NULL, 1);
   G__memfunc_setup("SetPattern",1034,G__kpsa_Dict_165_0_16, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<int,allocator<int> >' 'vector<int>' 1 - aPulse", "Set the pattern", (void*) NULL, 1);
   G__memfunc_setup("InitializeMembers",1757,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("KPatternRemoval", 1535, G__kpsa_Dict_165_0_18, (int) ('i'), G__get_linked_tagnum(&G__kpsa_DictLN_KPatternRemoval), -1, 0, 1, 1, 1, 0, "u 'KPatternRemoval' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~KPatternRemoval", 1661, G__kpsa_Dict_165_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__kpsa_Dict_165_0_20, (int) ('u'), G__get_linked_tagnum(&G__kpsa_DictLN_KPatternRemoval), -1, 1, 1, 1, 1, 0, "u 'KPatternRemoval' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncKPulseAnalysisChain(void) {
   /* KPulseAnalysisChain */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KPulseAnalysisChain));
   G__memfunc_setup("KPulseAnalysisChain",1915,G__kpsa_Dict_166_0_1, 105, G__get_linked_tagnum(&G__kpsa_DictLN_KPulseAnalysisChain), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunAll",590,G__kpsa_Dict_166_0_2, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AddProcessor",1225,G__kpsa_Dict_166_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "U 'KPsaProcessor' - 0 - p", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AddProcessorAt",1406,G__kpsa_Dict_166_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'KPsaProcessor' - 0 - p h - - 0 - index", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitializeMembers",1757,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("KPulseAnalysisChain", 1915, G__kpsa_Dict_166_0_6, (int) ('i'), G__get_linked_tagnum(&G__kpsa_DictLN_KPulseAnalysisChain), -1, 0, 1, 1, 1, 0, "u 'KPulseAnalysisChain' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~KPulseAnalysisChain", 2041, G__kpsa_Dict_166_0_7, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__kpsa_Dict_166_0_8, (int) ('u'), G__get_linked_tagnum(&G__kpsa_DictLN_KPulseAnalysisChain), -1, 1, 1, 1, 1, 0, "u 'KPulseAnalysisChain' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncKRealToHalfComplexDFT(void) {
   /* KRealToHalfComplexDFT */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KRealToHalfComplexDFT));
   G__memfunc_setup("KRealToHalfComplexDFT",1987,G__kpsa_Dict_171_0_1, 105, G__get_linked_tagnum(&G__kpsa_DictLN_KRealToHalfComplexDFT), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RunProcess",1044,(G__InterfaceMethod) NULL,103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInputPulse",1349,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - aPulse", "Set the input pulse", (void*) NULL, 1);
   G__memfunc_setup("SetInputPulse",1349,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<short,allocator<short> >' 'vector<short>' 11 - aPulse", "Set the input pulse ", (void*) NULL, 1);
   G__memfunc_setup("SetInputPulse",1349,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<float,allocator<float> >' 'vector<float>' 11 - aPulse", "Set the input pulse", (void*) NULL, 1);
   G__memfunc_setup("SetInputPulse",1349,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<int,allocator<int> >' 'vector<int>' 11 - aPulse", "Set the input pulse", (void*) NULL, 1);
   G__memfunc_setup("SetInputPulse",1349,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - aFile", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetFFTWFlag",989,G__kpsa_Dict_171_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 '0' aFlag", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetIn_fft",886,G__kpsa_Dict_171_0_9, 68, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOut_fft",1015,G__kpsa_Dict_171_0_10, 68, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetFFTWFlag",977,G__kpsa_Dict_171_0_11, 67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitializeMembers",1757,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MapFlag",664,(G__InterfaceMethod) NULL, 104, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AllocateFFTArrays",1655,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FillFFTArrays",1241,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetFFTWPlan",1006,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CopyArrayToOutput",1774,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CalculateFFT",1134,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("KRealToHalfComplexDFT", 1987, G__kpsa_Dict_171_0_19, (int) ('i'), 
G__get_linked_tagnum(&G__kpsa_DictLN_KRealToHalfComplexDFT), -1, 0, 1, 1, 1, 0, "u 'KRealToHalfComplexDFT' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~KRealToHalfComplexDFT", 2113, G__kpsa_Dict_171_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__kpsa_Dict_171_0_21, (int) ('u'), G__get_linked_tagnum(&G__kpsa_DictLN_KRealToHalfComplexDFT), -1, 1, 1, 1, 1, 0, "u 'KRealToHalfComplexDFT' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunckpsa_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalkpsa_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funckpsa_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__kpsa_DictLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_KPsaProcessor = { "KPsaProcessor" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_KBaselineRemoval = { "KBaselineRemoval" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_KPatternRemoval = { "KPatternRemoval" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_KPulseAnalysisChain = { "KPulseAnalysisChain" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_vectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgR = { "vector<KPsaProcessor*,allocator<KPsaProcessor*> >" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_reverse_iteratorlEvectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<KPsaProcessor*,allocator<KPsaProcessor*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__kpsa_DictLN_KRealToHalfComplexDFT = { "KRealToHalfComplexDFT" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablekpsa_Dict() {
  G__kpsa_DictLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__kpsa_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__kpsa_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__kpsa_DictLN_string.tagnum = -1 ;
  G__kpsa_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__kpsa_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__kpsa_DictLN_KPsaProcessor.tagnum = -1 ;
  G__kpsa_DictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__kpsa_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__kpsa_DictLN_KBaselineRemoval.tagnum = -1 ;
  G__kpsa_DictLN_KPatternRemoval.tagnum = -1 ;
  G__kpsa_DictLN_KPulseAnalysisChain.tagnum = -1 ;
  G__kpsa_DictLN_vectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgR.tagnum = -1 ;
  G__kpsa_DictLN_reverse_iteratorlEvectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__kpsa_DictLN_KRealToHalfComplexDFT.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablekpsa_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__kpsa_DictLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__kpsa_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__kpsa_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__kpsa_DictLN_string);
   G__get_linked_tagnum_fwd(&G__kpsa_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__kpsa_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KPsaProcessor),sizeof(KPsaProcessor),-1,1281,(char*)NULL,G__setup_memvarKPsaProcessor,G__setup_memfuncKPsaProcessor);
   G__get_linked_tagnum_fwd(&G__kpsa_DictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__kpsa_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KBaselineRemoval),sizeof(KBaselineRemoval),-1,1280,(char*)NULL,G__setup_memvarKBaselineRemoval,G__setup_memfuncKBaselineRemoval);
   G__tagtable_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KPatternRemoval),sizeof(KPatternRemoval),-1,1280,(char*)NULL,G__setup_memvarKPatternRemoval,G__setup_memfuncKPatternRemoval);
   G__tagtable_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KPulseAnalysisChain),sizeof(KPulseAnalysisChain),-1,1280,(char*)NULL,G__setup_memvarKPulseAnalysisChain,G__setup_memfuncKPulseAnalysisChain);
   G__get_linked_tagnum_fwd(&G__kpsa_DictLN_vectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgR);
   G__get_linked_tagnum_fwd(&G__kpsa_DictLN_reverse_iteratorlEvectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__kpsa_DictLN_KRealToHalfComplexDFT),sizeof(KRealToHalfComplexDFT),-1,1280,(char*)NULL,G__setup_memvarKRealToHalfComplexDFT,G__setup_memfuncKRealToHalfComplexDFT);
}
extern "C" void G__cpp_setupkpsa_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupkpsa_Dict()");
  G__set_cpp_environmentkpsa_Dict();
  G__cpp_setup_tagtablekpsa_Dict();

  G__cpp_setup_inheritancekpsa_Dict();

  G__cpp_setup_typetablekpsa_Dict();

  G__cpp_setup_memvarkpsa_Dict();

  G__cpp_setup_memfunckpsa_Dict();
  G__cpp_setup_globalkpsa_Dict();
  G__cpp_setup_funckpsa_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunckpsa_Dict();
  return;
}
class G__cpp_setup_initkpsa_Dict {
  public:
    G__cpp_setup_initkpsa_Dict() { G__add_setup_func("kpsa_Dict",(G__incsetup)(&G__cpp_setupkpsa_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initkpsa_Dict() { G__remove_setup_func("kpsa_Dict"); }
};
G__cpp_setup_initkpsa_Dict G__cpp_setup_initializerkpsa_Dict;

