/********************************************************************
* kpsa/kpsa_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error kpsa/kpsa_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablekpsa_Dict();
extern void G__cpp_setup_inheritancekpsa_Dict();
extern void G__cpp_setup_typetablekpsa_Dict();
extern void G__cpp_setup_memvarkpsa_Dict();
extern void G__cpp_setup_globalkpsa_Dict();
extern void G__cpp_setup_memfunckpsa_Dict();
extern void G__cpp_setup_funckpsa_Dict();
extern void G__set_cpp_environmentkpsa_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "kpsa/KBaselineRemoval.h"
#include "kpsa/KPatternRemoval.h"
#include "kpsa/KPsaProcessor.h"
#include "kpsa/KPulseAnalysisChain.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__kpsa_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__kpsa_DictLN_string;
extern G__linked_taginfo G__kpsa_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__kpsa_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__kpsa_DictLN_KPsaProcessor;
extern G__linked_taginfo G__kpsa_DictLN_KBaselineRemoval;
extern G__linked_taginfo G__kpsa_DictLN_KPatternRemoval;
extern G__linked_taginfo G__kpsa_DictLN_KPulseAnalysisChain;
extern G__linked_taginfo G__kpsa_DictLN_vectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgR;
extern G__linked_taginfo G__kpsa_DictLN_reverse_iteratorlEvectorlEKPsaProcessormUcOallocatorlEKPsaProcessormUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
