//
// File generated by /Users/adam/softwareDev/root/v5.28.00/bin/rootcint at Mon Feb  7 17:06:51 2011

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME kdatabasedIkdatabase_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "kdatabase_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void KCouchDB_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_KCouchDB(void *p = 0);
   static void *newArray_KCouchDB(Long_t size, void *p);
   static void delete_KCouchDB(void *p);
   static void deleteArray_KCouchDB(void *p);
   static void destruct_KCouchDB(void *p);
   static void streamer_KCouchDB(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::KCouchDB*)
   {
      ::KCouchDB *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::KCouchDB >(0);
      static ::ROOT::TGenericClassInfo 
         instance("KCouchDB", ::KCouchDB::Class_Version(), "./kdatabase/KCouchDB.h", 18,
                  typeid(::KCouchDB), DefineBehavior(ptr, ptr),
                  &::KCouchDB::Dictionary, isa_proxy, 0,
                  sizeof(::KCouchDB) );
      instance.SetNew(&new_KCouchDB);
      instance.SetNewArray(&newArray_KCouchDB);
      instance.SetDelete(&delete_KCouchDB);
      instance.SetDeleteArray(&deleteArray_KCouchDB);
      instance.SetDestructor(&destruct_KCouchDB);
      instance.SetStreamerFunc(&streamer_KCouchDB);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::KCouchDB*)
   {
      return GenerateInitInstanceLocal((::KCouchDB*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::KCouchDB*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *KCouchDB::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *KCouchDB::Class_Name()
{
   return "KCouchDB";
}

//______________________________________________________________________________
const char *KCouchDB::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::KCouchDB*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int KCouchDB::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::KCouchDB*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void KCouchDB::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::KCouchDB*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *KCouchDB::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::KCouchDB*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void KCouchDB::Streamer(TBuffer &R__b)
{
   // Stream an object of class KCouchDB.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      R__b.CheckByteCount(R__s, R__c, KCouchDB::IsA());
   } else {
      R__c = R__b.WriteVersion(KCouchDB::IsA(), kTRUE);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void KCouchDB::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class KCouchDB.
      TClass *R__cl = ::KCouchDB::IsA();
      if (R__cl || R__insp.IsA()) { }
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_KCouchDB(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KCouchDB : new ::KCouchDB;
   }
   static void *newArray_KCouchDB(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KCouchDB[nElements] : new ::KCouchDB[nElements];
   }
   // Wrapper around operator delete
   static void delete_KCouchDB(void *p) {
      delete ((::KCouchDB*)p);
   }
   static void deleteArray_KCouchDB(void *p) {
      delete [] ((::KCouchDB*)p);
   }
   static void destruct_KCouchDB(void *p) {
      typedef ::KCouchDB current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_KCouchDB(TBuffer &buf, void *obj) {
      ((::KCouchDB*)obj)->::KCouchDB::Streamer(buf);
   }
} // end of namespace ROOT for class ::KCouchDB

/********************************************************
* kdatabase/kdatabase_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablekdatabase_Dict();

extern "C" void G__set_cpp_environmentkdatabase_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("kdatabase/KCouchDB.h");
  G__cpp_reset_tagtablekdatabase_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevkdatabase_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* KCouchDB */
static int G__kdatabase_Dict_176_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KCouchDB* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KCouchDB[n];
     } else {
       p = new((void*) gvp) KCouchDB[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KCouchDB;
     } else {
       p = new((void*) gvp) KCouchDB;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__kdatabase_DictLN_KCouchDB));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 89, (long) ((KCouchDB*) G__getstructoffset())->PythonTest());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) KCouchDB::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KCouchDB::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) KCouchDB::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      KCouchDB::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const KCouchDB*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KCouchDB*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KCouchDB*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KCouchDB*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KCouchDB::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) KCouchDB::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KCouchDB::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__kdatabase_Dict_176_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) KCouchDB::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__kdatabase_Dict_176_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   KCouchDB* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new KCouchDB(*(KCouchDB*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__kdatabase_DictLN_KCouchDB));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef KCouchDB G__TKCouchDB;
static int G__kdatabase_Dict_176_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (KCouchDB*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((KCouchDB*) (soff+(sizeof(KCouchDB)*i)))->~G__TKCouchDB();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (KCouchDB*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((KCouchDB*) (soff))->~G__TKCouchDB();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__kdatabase_Dict_176_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KCouchDB* dest = (KCouchDB*) G__getstructoffset();
   *dest = *(KCouchDB*) libp->para[0].ref;
   const KCouchDB& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* KCouchDB */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunckdatabase_Dict {
 public:
  G__Sizep2memfunckdatabase_Dict(): p(&G__Sizep2memfunckdatabase_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunckdatabase_Dict::*p)();
};

size_t G__get_sizep2memfunckdatabase_Dict()
{
  G__Sizep2memfunckdatabase_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancekdatabase_Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablekdatabase_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__kdatabase_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__kdatabase_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__kdatabase_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__kdatabase_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__kdatabase_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__kdatabase_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__kdatabase_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__kdatabase_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__kdatabase_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__kdatabase_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* KCouchDB */
static void G__setup_memvarKCouchDB(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__kdatabase_DictLN_KCouchDB));
   { KCouchDB *p; p=(KCouchDB*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__kdatabase_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarkdatabase_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncKCouchDB(void) {
   /* KCouchDB */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__kdatabase_DictLN_KCouchDB));
   G__memfunc_setup("KCouchDB",707,G__kdatabase_Dict_176_0_1, 105, G__get_linked_tagnum(&G__kdatabase_DictLN_KCouchDB), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PythonTest",1058,G__kdatabase_Dict_176_0_2, 89, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__kdatabase_Dict_176_0_3, 85, G__get_linked_tagnum(&G__kdatabase_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&KCouchDB::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__kdatabase_Dict_176_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KCouchDB::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__kdatabase_Dict_176_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&KCouchDB::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__kdatabase_Dict_176_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&KCouchDB::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__kdatabase_Dict_176_0_7, 85, G__get_linked_tagnum(&G__kdatabase_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__kdatabase_Dict_176_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__kdatabase_Dict_176_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__kdatabase_Dict_176_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__kdatabase_Dict_176_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KCouchDB::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__kdatabase_Dict_176_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&KCouchDB::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__kdatabase_Dict_176_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KCouchDB::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__kdatabase_Dict_176_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&KCouchDB::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("KCouchDB", 707, G__kdatabase_Dict_176_0_15, (int) ('i'), G__get_linked_tagnum(&G__kdatabase_DictLN_KCouchDB), -1, 0, 1, 1, 1, 0, "u 'KCouchDB' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~KCouchDB", 833, G__kdatabase_Dict_176_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__kdatabase_Dict_176_0_17, (int) ('u'), G__get_linked_tagnum(&G__kdatabase_DictLN_KCouchDB), -1, 1, 1, 1, 1, 0, "u 'KCouchDB' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunckdatabase_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalkdatabase_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funckdatabase_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__kdatabase_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__kdatabase_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__kdatabase_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__kdatabase_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__kdatabase_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__kdatabase_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__kdatabase_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__kdatabase_DictLN_KCouchDB = { "KCouchDB" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablekdatabase_Dict() {
  G__kdatabase_DictLN_TClass.tagnum = -1 ;
  G__kdatabase_DictLN_TBuffer.tagnum = -1 ;
  G__kdatabase_DictLN_TMemberInspector.tagnum = -1 ;
  G__kdatabase_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__kdatabase_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__kdatabase_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__kdatabase_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__kdatabase_DictLN_KCouchDB.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablekdatabase_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__kdatabase_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__kdatabase_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__kdatabase_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__kdatabase_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__kdatabase_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__kdatabase_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__kdatabase_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__kdatabase_DictLN_KCouchDB),sizeof(KCouchDB),-1,1280,(char*)NULL,G__setup_memvarKCouchDB,G__setup_memfuncKCouchDB);
}
extern "C" void G__cpp_setupkdatabase_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupkdatabase_Dict()");
  G__set_cpp_environmentkdatabase_Dict();
  G__cpp_setup_tagtablekdatabase_Dict();

  G__cpp_setup_inheritancekdatabase_Dict();

  G__cpp_setup_typetablekdatabase_Dict();

  G__cpp_setup_memvarkdatabase_Dict();

  G__cpp_setup_memfunckdatabase_Dict();
  G__cpp_setup_globalkdatabase_Dict();
  G__cpp_setup_funckdatabase_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunckdatabase_Dict();
  return;
}
class G__cpp_setup_initkdatabase_Dict {
  public:
    G__cpp_setup_initkdatabase_Dict() { G__add_setup_func("kdatabase_Dict",(G__incsetup)(&G__cpp_setupkdatabase_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initkdatabase_Dict() { G__remove_setup_func("kdatabase_Dict"); }
};
G__cpp_setup_initkdatabase_Dict G__cpp_setup_initializerkdatabase_Dict;

