# Definitions specific to KDATA and this architecture
#
# AC 08/19/10


##### Changes to C++ compiler flags #####

# change compiler options (ROOT default for linux is -O)
OPT            := -g -O3

# add KDATA-specific compiler switches for this platform
KDATA_FLAGS     := 

EXTRALIBS      := -lrt

##### Extra fortran flags #####

F77FLAGS       += -fno-f2c -fno-second-underscore -fPIC -march=i686 -mieee-fp -ffloat-store

#####

F77LD						= $(F77)
