/********************************************************************
* ksamba/ksamba_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ksamba/ksamba_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableksamba_Dict();
extern void G__cpp_setup_inheritanceksamba_Dict();
extern void G__cpp_setup_typetableksamba_Dict();
extern void G__cpp_setup_memvarksamba_Dict();
extern void G__cpp_setup_globalksamba_Dict();
extern void G__cpp_setup_memfuncksamba_Dict();
extern void G__cpp_setup_funcksamba_Dict();
extern void G__set_cpp_environmentksamba_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ksamba/KSamba2KData.h"
#include "ksamba/KSambaDataObject.h"
#include "ksamba/KSambaDetector.h"
#include "ksamba/KSambaDetectorChannel.h"
#include "ksamba/KSambaEvent.h"
#include "ksamba/KSambaEventReader.h"
#include "ksamba/KSambaHeader.h"
#include "ksamba/KSambaHeaderReader.h"
#include "ksamba/KSambaPulse.h"
#include "ksamba/KSambaReader.h"
#include "ksamba/KSambaRun.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ksamba_DictLN_TClass;
extern G__linked_taginfo G__ksamba_DictLN_TBuffer;
extern G__linked_taginfo G__ksamba_DictLN_TMemberInspector;
extern G__linked_taginfo G__ksamba_DictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__ksamba_DictLN_string;
extern G__linked_taginfo G__ksamba_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ksamba_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ksamba_DictLN_KSamba2KData;
extern G__linked_taginfo G__ksamba_DictLN_KSambaDataObject;
extern G__linked_taginfo G__ksamba_DictLN_KSambaDetector;
extern G__linked_taginfo G__ksamba_DictLN_KSambaDetectorChannel;
extern G__linked_taginfo G__ksamba_DictLN_KSambaEvent;
extern G__linked_taginfo G__ksamba_DictLN_KSambaEventReader;
extern G__linked_taginfo G__ksamba_DictLN_KSambaHeader;
extern G__linked_taginfo G__ksamba_DictLN_KSambaHeaderReader;
extern G__linked_taginfo G__ksamba_DictLN_KSambaPulse;
extern G__linked_taginfo G__ksamba_DictLN_KSambaReader;
extern G__linked_taginfo G__ksamba_DictLN_KSambaRun;

/* STUB derived class for protected member access */
