//
// File generated by /Users/adam/softwareDev/root/v5.26.00b/bin/rootcint at Fri Aug 20 23:06:45 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "KTMP_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void KMyTemplateClass_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_KMyTemplateClass(void *p = 0);
   static void *newArray_KMyTemplateClass(Long_t size, void *p);
   static void delete_KMyTemplateClass(void *p);
   static void deleteArray_KMyTemplateClass(void *p);
   static void destruct_KMyTemplateClass(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::KMyTemplateClass*)
   {
      ::KMyTemplateClass *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::KMyTemplateClass >(0);
      static ::ROOT::TGenericClassInfo 
         instance("KMyTemplateClass", ::KMyTemplateClass::Class_Version(), "ktemplate/KMyTemplateClass.h", 14,
                  typeid(::KMyTemplateClass), DefineBehavior(ptr, ptr),
                  &::KMyTemplateClass::Dictionary, isa_proxy, 0,
                  sizeof(::KMyTemplateClass) );
      instance.SetNew(&new_KMyTemplateClass);
      instance.SetNewArray(&newArray_KMyTemplateClass);
      instance.SetDelete(&delete_KMyTemplateClass);
      instance.SetDeleteArray(&deleteArray_KMyTemplateClass);
      instance.SetDestructor(&destruct_KMyTemplateClass);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::KMyTemplateClass*)
   {
      return GenerateInitInstanceLocal((::KMyTemplateClass*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::KMyTemplateClass*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *KMyTemplateClass::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *KMyTemplateClass::Class_Name()
{
   return "KMyTemplateClass";
}

//______________________________________________________________________________
const char *KMyTemplateClass::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::KMyTemplateClass*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int KMyTemplateClass::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::KMyTemplateClass*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void KMyTemplateClass::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::KMyTemplateClass*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *KMyTemplateClass::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::KMyTemplateClass*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void KMyTemplateClass::Streamer(TBuffer &R__b)
{
   // Stream an object of class KMyTemplateClass.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      R__b.CheckByteCount(R__s, R__c, KMyTemplateClass::IsA());
   } else {
      R__c = R__b.WriteVersion(KMyTemplateClass::IsA(), kTRUE);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void KMyTemplateClass::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class KMyTemplateClass.
      TClass *R__cl = ::KMyTemplateClass::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_KMyTemplateClass(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KMyTemplateClass : new ::KMyTemplateClass;
   }
   static void *newArray_KMyTemplateClass(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::KMyTemplateClass[nElements] : new ::KMyTemplateClass[nElements];
   }
   // Wrapper around operator delete
   static void delete_KMyTemplateClass(void *p) {
      delete ((::KMyTemplateClass*)p);
   }
   static void deleteArray_KMyTemplateClass(void *p) {
      delete [] ((::KMyTemplateClass*)p);
   }
   static void destruct_KMyTemplateClass(void *p) {
      typedef ::KMyTemplateClass current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::KMyTemplateClass

/********************************************************
* ktemplate/KTMP_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableKTMP_Dict();

extern "C" void G__set_cpp_environmentKTMP_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ktemplate/KMyTemplateClass.h");
  G__cpp_reset_tagtableKTMP_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevKTMP_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* KMyTemplateClass */
static int G__KTMP_Dict_149_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KMyTemplateClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KMyTemplateClass[n];
     } else {
       p = new((void*) gvp) KMyTemplateClass[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new KMyTemplateClass;
     } else {
       p = new((void*) gvp) KMyTemplateClass;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__KTMP_DictLN_KMyTemplateClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) KMyTemplateClass::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KMyTemplateClass::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) KMyTemplateClass::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      KMyTemplateClass::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const KMyTemplateClass*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KMyTemplateClass*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref, (char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KMyTemplateClass*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((KMyTemplateClass*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KMyTemplateClass::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) KMyTemplateClass::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) KMyTemplateClass::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__KTMP_Dict_149_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) KMyTemplateClass::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__KTMP_Dict_149_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   KMyTemplateClass* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new KMyTemplateClass(*(KMyTemplateClass*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__KTMP_DictLN_KMyTemplateClass));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef KMyTemplateClass G__TKMyTemplateClass;
static int G__KTMP_Dict_149_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (KMyTemplateClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((KMyTemplateClass*) (soff+(sizeof(KMyTemplateClass)*i)))->~G__TKMyTemplateClass();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (KMyTemplateClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((KMyTemplateClass*) (soff))->~G__TKMyTemplateClass();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__KTMP_Dict_149_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   KMyTemplateClass* dest = (KMyTemplateClass*) G__getstructoffset();
   *dest = *(KMyTemplateClass*) libp->para[0].ref;
   const KMyTemplateClass& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* KMyTemplateClass */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncKTMP_Dict {
 public:
  G__Sizep2memfuncKTMP_Dict(): p(&G__Sizep2memfuncKTMP_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncKTMP_Dict::*p)();
};

size_t G__get_sizep2memfuncKTMP_Dict()
{
  G__Sizep2memfuncKTMP_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceKTMP_Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableKTMP_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__KTMP_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__KTMP_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KTMP_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__KTMP_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__KTMP_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__KTMP_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* KMyTemplateClass */
static void G__setup_memvarKMyTemplateClass(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__KTMP_DictLN_KMyTemplateClass));
   { KMyTemplateClass *p; p=(KMyTemplateClass*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__KTMP_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarKTMP_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncKMyTemplateClass(void) {
   /* KMyTemplateClass */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__KTMP_DictLN_KMyTemplateClass));
   G__memfunc_setup("KMyTemplateClass",1603,G__KTMP_Dict_149_0_1, 105, G__get_linked_tagnum(&G__KTMP_DictLN_KMyTemplateClass), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__KTMP_Dict_149_0_2, 85, G__get_linked_tagnum(&G__KTMP_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&KMyTemplateClass::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__KTMP_Dict_149_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KMyTemplateClass::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__KTMP_Dict_149_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&KMyTemplateClass::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__KTMP_Dict_149_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&KMyTemplateClass::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__KTMP_Dict_149_0_6, 85, G__get_linked_tagnum(&G__KTMP_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__KTMP_Dict_149_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__KTMP_Dict_149_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__KTMP_Dict_149_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__KTMP_Dict_149_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KMyTemplateClass::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__KTMP_Dict_149_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&KMyTemplateClass::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__KTMP_Dict_149_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&KMyTemplateClass::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__KTMP_Dict_149_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&KMyTemplateClass::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("KMyTemplateClass", 1603, G__KTMP_Dict_149_0_14, (int) ('i'), G__get_linked_tagnum(&G__KTMP_DictLN_KMyTemplateClass), -1, 0, 1, 1, 1, 0, "u 'KMyTemplateClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~KMyTemplateClass", 1729, G__KTMP_Dict_149_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__KTMP_Dict_149_0_16, (int) ('u'), G__get_linked_tagnum(&G__KTMP_DictLN_KMyTemplateClass), -1, 1, 1, 1, 1, 0, "u 'KMyTemplateClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncKTMP_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalKTMP_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcKTMP_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__KTMP_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__KTMP_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__KTMP_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__KTMP_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__KTMP_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__KTMP_DictLN_KMyTemplateClass = { "KMyTemplateClass" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableKTMP_Dict() {
  G__KTMP_DictLN_TClass.tagnum = -1 ;
  G__KTMP_DictLN_TBuffer.tagnum = -1 ;
  G__KTMP_DictLN_TMemberInspector.tagnum = -1 ;
  G__KTMP_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__KTMP_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__KTMP_DictLN_KMyTemplateClass.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableKTMP_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__KTMP_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__KTMP_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__KTMP_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__KTMP_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__KTMP_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__KTMP_DictLN_KMyTemplateClass),sizeof(KMyTemplateClass),-1,1280,(char*)NULL,G__setup_memvarKMyTemplateClass,G__setup_memfuncKMyTemplateClass);
}
extern "C" void G__cpp_setupKTMP_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupKTMP_Dict()");
  G__set_cpp_environmentKTMP_Dict();
  G__cpp_setup_tagtableKTMP_Dict();

  G__cpp_setup_inheritanceKTMP_Dict();

  G__cpp_setup_typetableKTMP_Dict();

  G__cpp_setup_memvarKTMP_Dict();

  G__cpp_setup_memfuncKTMP_Dict();
  G__cpp_setup_globalKTMP_Dict();
  G__cpp_setup_funcKTMP_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncKTMP_Dict();
  return;
}
class G__cpp_setup_initKTMP_Dict {
  public:
    G__cpp_setup_initKTMP_Dict() { G__add_setup_func("KTMP_Dict",(G__incsetup)(&G__cpp_setupKTMP_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initKTMP_Dict() { G__remove_setup_func("KTMP_Dict"); }
};
G__cpp_setup_initKTMP_Dict G__cpp_setup_initializerKTMP_Dict;

